### ISSUE TITLE
Expand button overlaps with text

### ISSUE THREAD

**Issue by kyleconroy** [SFDigitalServices/sfgov#468]
In the "Special Cases" section of the [Stay home except for essential needs](https://sf.gov/stay-home-except-essential-needs) page, the text and the expansion symbol "+" overlap.

![Screen Shot 2020-03-16 at 19 09 44](https://user-images.githubusercontent.com/34893/76815040-ba464700-67b9-11ea-8d0a-3a96a16676e5.png)

My setup:
macOS 10.14.6
Firefox 74.0 with uBlock Origin

This is the first issue I've report about sf.gov. Please let me know if you need any additional information.

**Comment by nicolesque** [comment]
Thank you, @kyleconroy! I'm closing this on GitHub, but trust we are tracking it in our JIRA and will prioritize and schedule it there.
