### ISSUE TITLE
Availability button not centered

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/sfgov#824]
![Live (actual)](https://user-images.githubusercontent.com/11983227/108775091-773a3b00-7515-11eb-9a01-ce67fcbc5c3d.jpeg)

![Design (expected)](https://user-images.githubusercontent.com/11983227/108775109-7d301c00-7515-11eb-8e5c-3392541cb068.png)

**Comment by zakiya** [comment]
Centered on mobile, left aligned on desktop per the comps.

**Comment by cschlessinger** [comment]
Passes
