### ISSUE TITLE
Update "no results found" state

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/sfgov#826]
![Screen Shot 2021-02-22 at 2 26 38 PM](https://user-images.githubusercontent.com/11983227/108778270-fa5d9000-7519-11eb-8c90-234b2e9ebc2c.png)

[Figma](https://www.figma.com/file/ZpEVJd6jGnRDdf5SMrypDQ/Vaccines?node-id=420%3A0)

Link for "Remove some of the filters to find more sites. You can also see more options to get vaccinated." should go to sf.gov/getvaccinated

**Comment by zakiya** [comment]
Ready for QA - I see I just the wrong text styling. Do you mind adding that to the styling bugs list?

**Comment by cschlessinger** [comment]
Sorry @zakiya I think there's a typo in your comment, are you saying there's a styling issue?

**Comment by zakiya** [comment]
Yes @cschlessinger  That's what I was trying to say. The "No sites match your search" text is a different font style from the comp.

**Comment by cschlessinger** [comment]
Got it, thanks, it's in row 10 of the spreadsheet. Will close this one
