### ISSUE TITLE
Styling bugs

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/sfgov#827]
https://docs.google.com/spreadsheets/d/185aTkBIrYKig8Xj2S7zdjl_xtisB0rbcS1C3PoEYYnM/edit#gid=1660987997

**Comment by zakiya** [comment]
@cschlessinger All the items in the design doc should be addressed except for rows 9 and 13.

**Comment by cschlessinger** [comment]
@zakiya on a PR branch or prod?

**Comment by zakiya** [comment]
@cschlessinger Sorry about that https://pr-836-sfgov.pantheonsite.io/vaccine-sites

**Comment by cschlessinger** [comment]
Passes
