### ISSUE TITLE
Info links are not displaying

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/sfgov#828]
There should be info links for Moscone and Produce Market that I see in the API but not on the page (the "Learn more about this location" link)
![Screen Shot 2021-02-22 at 2 36 12 PM](https://user-images.githubusercontent.com/11983227/108779160-507f0300-751b-11eb-8c3b-717112eafe9f.png)

**Comment by zakiya** [comment]
Ready for QA

**Comment by cschlessinger** [comment]
Fixed
