### ISSUE TITLE
Some Drupal translations are not taking

### ISSUE THREAD

**Issue by nicolesque** [SFDigitalServices/sfgov#830]
We translated strings in Drupal and some are not taking on the front end, even after we clear the cache.

**Spanish**
* "Ingles" should be "Inglés"
* Inconsistency with capitalizing available languages on drop-down (Chino is lowercase)

**Chinese**
* "Second dose" is not showing human translation
* "Only show sites open to the general public" "Only show sites with available appointments " and "Apply" are not showing human translation.
* CTA strings are not showing as human translation

**Comment by nicolesque** [comment]
@zakiya - Nicole is still looking but it seems like some strings are still not taking, you can see them noted here: https://docs.google.com/spreadsheets/d/185aTkBIrYKig8Xj2S7zdjl_xtisB0rbcS1C3PoEYYnM/edit#gid=1905127799

**Comment by nicolesque** [comment]
@akegan @zakiya - in Chinese only, the location **address** is being translated. Can we stop that from happening?

**Comment by zakiya** [comment]
@nicolesque Are there any remaining items for this task?

**Comment by nicolesque** [comment]
Nope! Closing.
