### ISSUE TITLE
Vaccine Sites  Dev Tasks

### ISSUE THREAD

**Issue by zakiya** [SFDigitalServices/sfgov#838]
https://pr-836-sfgov.pantheonsite.io/vaccine-sites

- [ ] Add support for Other Languages - filter
- [ ] Refreshing data should not require a cache clear.
- [ ] Exclude all Drupal strings from gtranslate
- [ ] Make endpoint url configurable
- [ ] Use dependency injection in the controller
- [ ] Collect strings
- [ ] Use drupal link functions instead of a tags in twig.
- [ ] Design medium - line 9 - box-shadow on checkboxes (sf.gov?)
- [ ] Design medium - line 11 - when check box labels wrap, they should align with text (sf.gov?)
- [x] Verify language query works (es, zh-hant, fil)
- [x] Show/hide Filters accordion

**Comment by nicolesque** [comment]
@zakiya are these in order?

**Comment by zakiya** [comment]
@nicolesque yes. If there's anything you think I should prioritize let me know. "Exclude all Drupal strings from gtranslate" is really a task for SF.gov. I think we'll need it eventually regardless of what happens with vaccine sites.

**Comment by cschlessinger** [comment]
Heads up, I'm going to move this all to Jira

**Comment by cschlessinger** [comment]
@zakiya I think I've brought all of these over to the new Jira - check it out [here](https://sfgovdt.jira.com/secure/RapidBoard.jspa?rapidView=130&projectKey=VAX&view=planning&selectedIssue=VAX-38&quickFilter=228&issueLimit=100) and if so, you can close this issue.

**Comment by cschlessinger** [comment]
Closing this as this should all be captured in Jira now
